<HTML>
<HEAD>
<TITLE>ADMIN</TITLE>
</HEAD>
<H1><CENTER><U>RAILWAY RESERVATION SYSTEM</U></CENTER></H1>
<BODY BGCOLOR="SKY BLUE" TEXT="BLACK">
<FORM ID='SAMPLE'METHOD='POST'ACTION=' '>
<P>
ADMINLOGIN
</P>
<P>
USERNAME*:<INPUT TYPE='TEXT' NAME='NAME'/>
</P>
<P>
EMAILID*:<INPUT TYPE='TEXT' NAME='EMAIL'/>
</P>
<P>
<INPUT TYPE='RESET'NAME='RESET' VALUE='RESETPASSWORD'/>
</P>
</FORM>
</BODY>
</HTML>